services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DMK\T3socials\:
    resource: '../Classes/*'
  #   exclude: 
  #     - '../Classes/Model/*'
  # DMK\T3socials\Model\Repository\:
  #   resource: '../Classes/Model/Repository/*'

  # DMK\T3socials\Service\NetworkService:
  #   public: true

  DMK\T3socials\Hook\TCEHook:
    public: true
